# Generated by Django 5.0.3 on 2024-03-07 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_announcement_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(),
        ),
    ]
