# Generated by Django 5.0.3 on 2024-03-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_announcement_contact_email_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
    ]
